//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7PracticeExample.GuestServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestServiceReference.GuestsWebServiceSoap")]
    public interface GuestsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _7PracticeExample.GuestServiceReference.HelloWorldResponse HelloWorld(_7PracticeExample.GuestServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.HelloWorldResponse> HelloWorldAsync(_7PracticeExample.GuestServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name phone from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGuest", ReplyAction="*")]
        _7PracticeExample.GuestServiceReference.AddGuestResponse AddGuest(_7PracticeExample.GuestServiceReference.AddGuestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGuest", ReplyAction="*")]
        System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.AddGuestResponse> AddGuestAsync(_7PracticeExample.GuestServiceReference.AddGuestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _7PracticeExample.GuestServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_7PracticeExample.GuestServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _7PracticeExample.GuestServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_7PracticeExample.GuestServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGuestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGuest", Namespace="http://tempuri.org/", Order=0)]
        public _7PracticeExample.GuestServiceReference.AddGuestRequestBody Body;
        
        public AddGuestRequest() {
        }
        
        public AddGuestRequest(_7PracticeExample.GuestServiceReference.AddGuestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGuestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool agree;
        
        public AddGuestRequestBody() {
        }
        
        public AddGuestRequestBody(string phone, string name, string email, bool agree) {
            this.phone = phone;
            this.name = name;
            this.email = email;
            this.agree = agree;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGuestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGuestResponse", Namespace="http://tempuri.org/", Order=0)]
        public _7PracticeExample.GuestServiceReference.AddGuestResponseBody Body;
        
        public AddGuestResponse() {
        }
        
        public AddGuestResponse(_7PracticeExample.GuestServiceReference.AddGuestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddGuestResponseBody {
        
        public AddGuestResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GuestsWebServiceSoapChannel : _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestsWebServiceSoapClient : System.ServiceModel.ClientBase<_7PracticeExample.GuestServiceReference.GuestsWebServiceSoap>, _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap {
        
        public GuestsWebServiceSoapClient() {
        }
        
        public GuestsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _7PracticeExample.GuestServiceReference.HelloWorldResponse _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap.HelloWorld(_7PracticeExample.GuestServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _7PracticeExample.GuestServiceReference.HelloWorldRequest inValue = new _7PracticeExample.GuestServiceReference.HelloWorldRequest();
            inValue.Body = new _7PracticeExample.GuestServiceReference.HelloWorldRequestBody();
            _7PracticeExample.GuestServiceReference.HelloWorldResponse retVal = ((_7PracticeExample.GuestServiceReference.GuestsWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.HelloWorldResponse> _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap.HelloWorldAsync(_7PracticeExample.GuestServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.HelloWorldResponse> HelloWorldAsync() {
            _7PracticeExample.GuestServiceReference.HelloWorldRequest inValue = new _7PracticeExample.GuestServiceReference.HelloWorldRequest();
            inValue.Body = new _7PracticeExample.GuestServiceReference.HelloWorldRequestBody();
            return ((_7PracticeExample.GuestServiceReference.GuestsWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _7PracticeExample.GuestServiceReference.AddGuestResponse _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap.AddGuest(_7PracticeExample.GuestServiceReference.AddGuestRequest request) {
            return base.Channel.AddGuest(request);
        }
        
        public void AddGuest(string phone, string name, string email, bool agree) {
            _7PracticeExample.GuestServiceReference.AddGuestRequest inValue = new _7PracticeExample.GuestServiceReference.AddGuestRequest();
            inValue.Body = new _7PracticeExample.GuestServiceReference.AddGuestRequestBody();
            inValue.Body.phone = phone;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.agree = agree;
            _7PracticeExample.GuestServiceReference.AddGuestResponse retVal = ((_7PracticeExample.GuestServiceReference.GuestsWebServiceSoap)(this)).AddGuest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.AddGuestResponse> _7PracticeExample.GuestServiceReference.GuestsWebServiceSoap.AddGuestAsync(_7PracticeExample.GuestServiceReference.AddGuestRequest request) {
            return base.Channel.AddGuestAsync(request);
        }
        
        public System.Threading.Tasks.Task<_7PracticeExample.GuestServiceReference.AddGuestResponse> AddGuestAsync(string phone, string name, string email, bool agree) {
            _7PracticeExample.GuestServiceReference.AddGuestRequest inValue = new _7PracticeExample.GuestServiceReference.AddGuestRequest();
            inValue.Body = new _7PracticeExample.GuestServiceReference.AddGuestRequestBody();
            inValue.Body.phone = phone;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.agree = agree;
            return ((_7PracticeExample.GuestServiceReference.GuestsWebServiceSoap)(this)).AddGuestAsync(inValue);
        }
    }
}
